insert into Cuisine (neighborhood_id, neighborhood_name) values (1, 'Longwood');
insert into Cuisine (neighborhood_id, neighborhood_name) values (2, 'Beacon Hill');
insert into Cuisine (neighborhood_id, neighborhood_name) values (3, 'Brookline');
insert into Cuisine (neighborhood_id, neighborhood_name) values (4, 'West Roxbury');
insert into Cuisine (neighborhood_id, neighborhood_name) values (5, 'Longwood');
insert into Cuisine (neighborhood_id, neighborhood_name) values (6, 'Longwood');
insert into Cuisine (neighborhood_id, neighborhood_name) values (7, 'Longwood');
insert into Cuisine (neighborhood_id, neighborhood_name) values (8, 'South Boston');
insert into Cuisine (neighborhood_id, neighborhood_name) values (9, 'Beacon Hill');
insert into Cuisine (neighborhood_id, neighborhood_name) values (10, 'Charlestown');
insert into Cuisine (neighborhood_id, neighborhood_name) values (11, 'Longwood');
insert into Cuisine (neighborhood_id, neighborhood_name) values (12, 'West Roxbury');
insert into Cuisine (neighborhood_id, neighborhood_name) values (13, 'Fenway');
insert into Cuisine (neighborhood_id, neighborhood_name) values (14, 'Roslindale');
insert into Cuisine (neighborhood_id, neighborhood_name) values (15, 'Chinatown');
insert into Cuisine (neighborhood_id, neighborhood_name) values (16, 'South End');
insert into Cuisine (neighborhood_id, neighborhood_name) values (17, 'South End');
insert into Cuisine (neighborhood_id, neighborhood_name) values (18, 'West Roxbury');
insert into Cuisine (neighborhood_id, neighborhood_name) values (19, 'South End');
insert into Cuisine (neighborhood_id, neighborhood_name) values (20, 'Beacon Hill');
insert into Cuisine (neighborhood_id, neighborhood_name) values (21, 'Mission Hill');
insert into Cuisine (neighborhood_id, neighborhood_name) values (22, 'Brookline');
insert into Cuisine (neighborhood_id, neighborhood_name) values (23, 'Mission Hill');
insert into Cuisine (neighborhood_id, neighborhood_name) values (24, 'West Roxbury');
insert into Cuisine (neighborhood_id, neighborhood_name) values (25, 'Kenmore');
insert into Cuisine (neighborhood_id, neighborhood_name) values (26, 'Roslindale');
insert into Cuisine (neighborhood_id, neighborhood_name) values (27, 'South Boston');
insert into Cuisine (neighborhood_id, neighborhood_name) values (28, 'Allston');
insert into Cuisine (neighborhood_id, neighborhood_name) values (29, 'Jamaica Plain');
insert into Cuisine (neighborhood_id, neighborhood_name) values (30, 'Fenway');
insert into Cuisine (neighborhood_id, neighborhood_name) values (31, 'Chinatown');
insert into Cuisine (neighborhood_id, neighborhood_name) values (32, 'Jamaica Plain');
insert into Cuisine (neighborhood_id, neighborhood_name) values (33, 'Cambridge');
insert into Cuisine (neighborhood_id, neighborhood_name) values (34, 'Dorchester');
insert into Cuisine (neighborhood_id, neighborhood_name) values (35, 'Brighton');
insert into Cuisine (neighborhood_id, neighborhood_name) values (36, 'Brookline');
insert into Cuisine (neighborhood_id, neighborhood_name) values (37, 'Downtown Crossing');
insert into Cuisine (neighborhood_id, neighborhood_name) values (38, 'Brookline');
insert into Cuisine (neighborhood_id, neighborhood_name) values (39, 'Allston');
insert into Cuisine (neighborhood_id, neighborhood_name) values (40, 'Mattapan');