insert into Neighborhood (neighborhood_id, neighborhood_name) values (1, 'Allston');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (2, 'Chinatown');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (3, 'Downtown Crossing');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (4, 'South End');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (5, 'Fenway');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (6, 'Brookline');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (7, 'Brighton');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (8, 'Symphony');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (9, 'Cambridge');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (10, 'Roxbury');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (11, 'Symphony');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (12, 'Back Bay');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (13, 'Back Bay');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (14, 'Fenway');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (15, 'Downtown Crossing');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (16, 'Jamaica Plain');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (17, 'Brookline');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (18, 'Symphony');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (19, 'Brookline');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (20, 'Allston');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (21, 'Roxbury');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (22, 'Mission Hill');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (23, 'Kenmore');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (24, 'Back Bay');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (25, 'Cambridge');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (26, 'South End');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (27, 'Longwood');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (28, 'Allston');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (29, 'Fenway');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (30, 'Back Bay');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (31, 'Kenmore');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (32, 'Cambridge');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (33, 'Mission Hill');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (34, 'Mission Hill');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (35, 'Back Bay');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (36, 'Fenway');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (37, 'Downtown Crossing');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (38, 'Mission Hill');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (39, 'Back Bay');
insert into Neighborhood (neighborhood_id, neighborhood_name) values (40, 'Fenway');
