USE huskybites;

insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (13, 1, 5.5, 'Standard fare, nothing extraordinary.', '2025-09-22', 'removed', 1);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 1, 8.0, 'Best place near campus for a quick bite.', '2025-01-09', 'removed', 2);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (31, 2, 3.3, 'The ambiance is perfect for a date night.', '2025-02-14', 'approved', 3);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 2, 7.8, 'Best place near campus for a quick bite.', '2024-09-30', 'approved', 4);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 3, 4.4, 'Excellent value for money.', '2024-07-20', 'pending', 5);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (34, 3, 2.6, 'Standard fare, nothing extraordinary.', '2025-06-20', 'removed', 6);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (20, 4, 3.3, 'Solid choice for a casual dinner.', '2025-03-27', 'approved', 7);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 4, 1.2, 'Hard to find parking nearby.', '2025-10-07', 'approved', 8);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (8, 5, 3.2, 'Hard to find parking nearby.', '2024-10-28', 'pending', 9);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 5, 10.0, 'Perfect for group hangouts.', '2025-01-05', 'pending', 10);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (19, 6, 9.2, 'The ambiance is perfect for a date night.', '2025-03-20', 'removed', 11);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (22, 6, 9.1, 'Will definitely be coming back again!', '2026-02-08', 'removed', 12);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (29, 7, 4.6, 'The spice level was just right.', '2026-01-05', 'pending', 13);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (16, 7, 6.7, 'Solid choice for a casual dinner.', '2026-02-07', 'approved', 14);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (5, 8, 2.9, 'Not many vegetarian options available.', '2025-04-10', 'approved', 15);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (32, 8, 6.6, 'Perfect for group hangouts.', '2026-01-04', 'pending', 16);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (28, 9, 1.7, 'Will definitely be coming back again!', '2025-09-07', 'approved', 17);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (33, 9, 7.1, 'Hard to find parking nearby.', '2026-03-10', 'approved', 18);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 10, 9.5, 'Solid choice for a casual dinner.', '2026-03-09', 'approved', 19);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (17, 10, 6.3, 'The seating area was quite cramped.', '2025-03-01', 'approved', 20);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (33, 11, 8.1, 'The service was a bit slow, but the food made up for it.', '2025-02-22', 'approved', 21);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (20, 11, 5.7, 'The service was a bit slow, but the food made up for it.', '2024-07-22', 'approved', 22);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (5, 12, 7.5, 'Will definitely be coming back again!', '2025-11-18', 'approved', 23);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (26, 12, 5.8, 'Solid choice for a casual dinner.', '2024-10-23', 'approved', 24);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (24, 13, 1.4, 'The wait time was longer than estimated.', '2025-10-23', 'removed', 25);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (20, 13, 3.7, 'Perfect for group hangouts.', '2025-01-03', 'approved', 26);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (10, 14, 8.9, 'Not many vegetarian options available.', '2024-05-26', 'approved', 27);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (21, 14, 5.0, 'A hidden gem in the neighborhood.', '2026-04-15', 'approved', 28);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (5, 15, 2.5, 'The dessert was the highlight of the meal.', '2025-08-03', 'removed', 29);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (12, 15, 3.9, 'The service was a bit slow, but the food made up for it.', '2024-02-20', 'approved', 30);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (22, 16, 3.8, 'Solid choice for a casual dinner.', '2025-12-01', 'approved', 31);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (17, 16, 4.7, 'The ambiance is perfect for a date night.', '2025-08-29', 'pending', 32);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (23, 17, 4.0, 'Excellent value for money.', '2025-07-28', 'approved', 33);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (23, 17, 7.0, 'Solid choice for a casual dinner.', '2024-07-14', 'approved', 34);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (2, 18, 8.6, 'The service was a bit slow, but the food made up for it.', '2025-05-24', 'approved', 35);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (31, 18, 3.9, 'Great food and atmosphere!', '2026-01-28', 'approved', 36);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (28, 19, 4.1, 'Very clean and well-maintained.', '2024-12-31', 'removed', 37);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (31, 19, 2.0, 'Great food and atmosphere!', '2024-10-14', 'approved', 38);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (33, 20, 1.9, 'Hard to find parking nearby.', '2025-01-07', 'removed', 39);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (33, 20, 8.1, 'The ambiance is perfect for a date night.', '2025-06-22', 'approved', 40);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (6, 21, 6.2, 'The seating area was quite cramped.', '2024-04-09', 'approved', 41);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (24, 21, 7.0, 'A bit overpriced for the portion size.', '2025-09-10', 'approved', 42);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (16, 22, 7.8, 'The dessert was the highlight of the meal.', '2024-11-05', 'approved', 43);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (22, 22, 1.7, 'A bit overpriced for the portion size.', '2025-07-12', 'approved', 44);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (18, 23, 8.0, 'Great food and atmosphere!', '2025-10-05', 'approved', 45);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (30, 23, 8.6, 'Not many vegetarian options available.', '2024-10-23', 'approved', 46);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 24, 8.6, 'Authentic flavors and friendly staff.', '2025-08-07', 'approved', 47);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 24, 2.0, 'The spice level was just right.', '2025-07-17', 'pending', 48);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (21, 25, 8.3, 'The dessert was the highlight of the meal.', '2025-09-03', 'approved', 49);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (29, 25, 7.1, 'Will definitely be coming back again!', '2025-05-25', 'approved', 50);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (13, 26, 4.0, 'The wait time was longer than estimated.', '2024-01-18', 'approved', 51);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (32, 26, 6.2, 'Excellent value for money.', '2025-12-03', 'pending', 52);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (6, 27, 1.1, 'A hidden gem in the neighborhood.', '2024-05-21', 'removed', 53);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (22, 27, 1.5, 'Authentic flavors and friendly staff.', '2026-03-14', 'approved', 54);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (9, 28, 8.9, 'The wait time was longer than estimated.', '2024-10-06', 'pending', 55);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (4, 28, 5.1, 'The ambiance is perfect for a date night.', '2026-03-22', 'approved', 56);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (1, 29, 2.7, 'The wait time was longer than estimated.', '2025-08-03', 'removed', 57);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 29, 1.6, 'Solid choice for a casual dinner.', '2025-01-17', 'pending', 58);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (20, 30, 7.4, 'Standard fare, nothing extraordinary.', '2024-02-27', 'approved', 59);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (9, 30, 5.1, 'Excellent value for money.', '2025-09-22', 'approved', 60);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (25, 31, 3.6, 'Solid choice for a casual dinner.', '2025-11-18', 'removed', 61);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (4, 31, 7.5, 'The service was a bit slow, but the food made up for it.', '2024-08-02', 'approved', 62);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (16, 32, 7.6, 'Highly recommend the signature dish.', '2024-05-20', 'pending', 63);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (38, 32, 8.8, 'Best place near campus for a quick bite.', '2024-02-01', 'removed', 64);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (10, 33, 3.9, 'Very clean and well-maintained.', '2026-01-02', 'pending', 65);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (4, 33, 8.0, 'Hard to find parking nearby.', '2025-09-15', 'approved', 66);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (36, 34, 2.8, 'Very clean and well-maintained.', '2025-12-13', 'approved', 67);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 34, 1.7, 'A hidden gem in the neighborhood.', '2026-01-18', 'pending', 68);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (31, 35, 4.0, 'Excellent value for money.', '2024-11-11', 'removed', 69);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (34, 35, 8.1, 'Perfect for group hangouts.', '2025-10-05', 'approved', 70);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 36, 4.8, 'The dessert was the highlight of the meal.', '2025-06-25', 'approved', 71);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 36, 2.5, 'The service was a bit slow, but the food made up for it.', '2025-12-17', 'approved', 72);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 37, 6.6, 'Very clean and well-maintained.', '2025-09-18', 'approved', 73);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (39, 37, 6.2, 'A bit overpriced for the portion size.', '2026-03-27', 'pending', 74);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (22, 38, 3.0, 'Excellent value for money.', '2024-03-31', 'removed', 75);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (36, 38, 2.3, 'Standard fare, nothing extraordinary.', '2024-03-08', 'approved', 76);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (33, 39, 1.7, 'The dessert was the highlight of the meal.', '2025-08-21', 'approved', 77);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (12, 39, 8.6, 'The spice level was just right.', '2025-03-06', 'approved', 78);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (24, 40, 6.8, 'Will definitely be coming back again!', '2024-05-20', 'pending', 79);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (40, 40, 9.4, 'The wait time was longer than estimated.', '2026-04-11', 'approved', 80);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (21, 41, 2.2, 'Very clean and well-maintained.', '2024-08-03', 'removed', 81);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (36, 41, 4.8, 'A hidden gem in the neighborhood.', '2025-02-05', 'approved', 82);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (21, 42, 7.1, 'Authentic flavors and friendly staff.', '2025-10-27', 'approved', 83);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (22, 42, 9.4, 'Solid choice for a casual dinner.', '2025-02-25', 'approved', 84);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (40, 43, 1.5, 'Great food and atmosphere!', '2024-01-19', 'approved', 85);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (26, 43, 6.2, 'Very clean and well-maintained.', '2025-01-26', 'pending', 86);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (37, 44, 2.7, 'The dessert was the highlight of the meal.', '2025-06-24', 'approved', 87);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (5, 44, 4.9, 'The service was a bit slow, but the food made up for it.', '2025-02-16', 'removed', 88);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (3, 45, 8.0, 'Not many vegetarian options available.', '2024-12-23', 'removed', 89);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (36, 45, 3.6, 'Perfect for group hangouts.', '2025-08-02', 'approved', 90);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (38, 46, 8.7, 'Not many vegetarian options available.', '2024-04-05', 'approved', 91);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (38, 46, 9.5, 'The wait time was longer than estimated.', '2025-07-27', 'removed', 92);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (18, 47, 8.0, 'Standard fare, nothing extraordinary.', '2024-01-08', 'removed', 93);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (9, 47, 2.4, 'A hidden gem in the neighborhood.', '2025-12-03', 'removed', 94);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (20, 48, 8.8, 'Not many vegetarian options available.', '2025-10-15', 'removed', 95);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 48, 3.2, 'Not many vegetarian options available.', '2025-03-11', 'approved', 96);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (38, 49, 7.1, 'Solid choice for a casual dinner.', '2024-07-27', 'approved', 97);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (5, 49, 2.5, 'Great food and atmosphere!', '2025-05-12', 'approved', 98);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (40, 50, 8.2, 'Standard fare, nothing extraordinary.', '2025-08-19', 'pending', 99);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 50, 7.5, 'Authentic flavors and friendly staff.', '2025-12-15', 'removed', 100);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 51, 1.8, 'The ambiance is perfect for a date night.', '2025-10-12', 'approved', 101);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (8, 51, 8.0, 'Authentic flavors and friendly staff.', '2024-02-28', 'approved', 102);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (1, 52, 7.8, 'The service was a bit slow, but the food made up for it.', '2025-01-31', 'approved', 103);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (39, 52, 4.6, 'Will definitely be coming back again!', '2025-10-04', 'approved', 104);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (34, 53, 6.6, 'Very clean and well-maintained.', '2025-12-28', 'removed', 105);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (4, 53, 4.2, 'The ambiance is perfect for a date night.', '2025-10-21', 'approved', 106);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (17, 54, 1.3, 'Very clean and well-maintained.', '2025-05-15', 'pending', 107);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (20, 54, 6.3, 'Authentic flavors and friendly staff.', '2026-01-12', 'approved', 108);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (18, 55, 3.1, 'The service was a bit slow, but the food made up for it.', '2025-06-17', 'approved', 109);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (22, 55, 8.0, 'Authentic flavors and friendly staff.', '2024-09-25', 'pending', 110);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (9, 56, 2.1, 'The seating area was quite cramped.', '2024-07-20', 'pending', 111);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (34, 56, 5.8, 'Highly recommend the signature dish.', '2024-06-21', 'approved', 112);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (31, 57, 8.3, 'Perfect for group hangouts.', '2024-10-05', 'approved', 113);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (3, 57, 1.7, 'Highly recommend the signature dish.', '2025-05-24', 'approved', 114);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (39, 58, 5.8, 'Highly recommend the signature dish.', '2024-04-14', 'approved', 115);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (40, 58, 9.3, 'A hidden gem in the neighborhood.', '2025-02-19', 'pending', 116);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (11, 59, 5.0, 'The ambiance is perfect for a date night.', '2024-04-26', 'pending', 117);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (13, 59, 4.7, 'Highly recommend the signature dish.', '2024-02-12', 'approved', 118);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (3, 60, 5.6, 'A bit overpriced for the portion size.', '2025-01-05', 'approved', 119);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (32, 60, 1.3, 'Great food and atmosphere!', '2026-02-23', 'pending', 120);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (26, 61, 1.8, 'A hidden gem in the neighborhood.', '2025-08-11', 'approved', 121);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (16, 61, 2.0, 'The spice level was just right.', '2025-08-03', 'approved', 122);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (4, 62, 1.6, 'Hard to find parking nearby.', '2024-04-19', 'pending', 123);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (24, 62, 9.6, 'Will definitely be coming back again!', '2024-07-19', 'approved', 124);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (9, 63, 1.1, 'Best place near campus for a quick bite.', '2024-12-11', 'removed', 125);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (8, 63, 1.3, 'Solid choice for a casual dinner.', '2024-11-04', 'approved', 126);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 64, 1.1, 'The seating area was quite cramped.', '2025-10-05', 'approved', 127);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (35, 64, 3.8, 'Highly recommend the signature dish.', '2024-07-27', 'approved', 128);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (12, 65, 7.6, 'The dessert was the highlight of the meal.', '2025-01-26', 'approved', 129);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (8, 65, 9.7, 'A hidden gem in the neighborhood.', '2024-03-20', 'removed', 130);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (13, 66, 4.5, 'Best place near campus for a quick bite.', '2024-07-26', 'removed', 131);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (4, 66, 5.5, 'The dessert was the highlight of the meal.', '2024-06-26', 'removed', 132);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (22, 67, 1.7, 'The dessert was the highlight of the meal.', '2024-07-27', 'approved', 133);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (39, 67, 8.2, 'A bit overpriced for the portion size.', '2024-09-13', 'pending', 134);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (19, 68, 3.0, 'Standard fare, nothing extraordinary.', '2025-02-22', 'approved', 135);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (35, 68, 2.4, 'Standard fare, nothing extraordinary.', '2025-09-01', 'approved', 136);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (8, 69, 5.2, 'Authentic flavors and friendly staff.', '2024-07-01', 'pending', 137);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (27, 69, 4.5, 'Solid choice for a casual dinner.', '2024-12-09', 'approved', 138);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (1, 70, 6.5, 'The ambiance is perfect for a date night.', '2024-01-23', 'approved', 139);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (7, 70, 3.1, 'Perfect for group hangouts.', '2024-03-29', 'removed', 140);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (40, 71, 6.5, 'The ambiance is perfect for a date night.', '2026-01-16', 'approved', 141);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (9, 71, 8.5, 'The wait time was longer than estimated.', '2025-05-18', 'pending', 142);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (25, 72, 5.4, 'Not many vegetarian options available.', '2024-09-11', 'approved', 143);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (33, 72, 7.7, 'Standard fare, nothing extraordinary.', '2025-04-23', 'pending', 144);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (17, 73, 6.1, 'The wait time was longer than estimated.', '2024-03-10', 'approved', 145);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (35, 73, 9.3, 'Best place near campus for a quick bite.', '2025-07-12', 'pending', 146);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (37, 74, 4.8, 'The service was a bit slow, but the food made up for it.', '2026-03-27', 'pending', 147);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (32, 74, 2.6, 'Solid choice for a casual dinner.', '2024-03-23', 'approved', 148);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (3, 75, 5.3, 'The seating area was quite cramped.', '2024-05-22', 'approved', 149);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (37, 75, 3.4, 'Very clean and well-maintained.', '2025-05-21', 'pending', 150);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (18, 76, 1.8, 'The ambiance is perfect for a date night.', '2024-12-06', 'pending', 151);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (13, 76, 1.5, 'Great food and atmosphere!', '2024-12-13', 'approved', 152);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (26, 77, 8.7, 'Will definitely be coming back again!', '2024-06-27', 'pending', 153);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (13, 77, 5.0, 'Great food and atmosphere!', '2024-11-29', 'approved', 154);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (6, 78, 1.8, 'Authentic flavors and friendly staff.', '2025-01-17', 'approved', 155);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (10, 78, 6.5, 'Great food and atmosphere!', '2026-03-03', 'approved', 156);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (5, 79, 1.4, 'Will definitely be coming back again!', '2024-11-11', 'approved', 157);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (1, 79, 8.4, 'A hidden gem in the neighborhood.', '2025-12-16', 'approved', 158);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (40, 80, 8.0, 'The dessert was the highlight of the meal.', '2024-02-18', 'approved', 159);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (32, 80, 7.9, 'The seating area was quite cramped.', '2025-01-07', 'pending', 160);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (21, 81, 1.2, 'Not many vegetarian options available.', '2024-04-22', 'pending', 161);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (31, 81, 4.9, 'The wait time was longer than estimated.', '2024-04-14', 'removed', 162);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (10, 82, 5.1, 'Will definitely be coming back again!', '2025-04-15', 'approved', 163);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (17, 82, 9.6, 'The ambiance is perfect for a date night.', '2025-08-04', 'approved', 164);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (22, 83, 3.7, 'The seating area was quite cramped.', '2024-05-14', 'approved', 165);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (13, 83, 6.2, 'Will definitely be coming back again!', '2025-03-24', 'approved', 166);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (32, 84, 8.7, 'The seating area was quite cramped.', '2024-06-15', 'approved', 167);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (37, 84, 2.5, 'Hard to find parking nearby.', '2026-01-22', 'pending', 168);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 85, 1.1, 'Authentic flavors and friendly staff.', '2025-04-30', 'approved', 169);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (33, 85, 5.1, 'A hidden gem in the neighborhood.', '2026-01-09', 'approved', 170);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (35, 86, 8.9, 'The ambiance is perfect for a date night.', '2025-10-27', 'pending', 171);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (28, 86, 4.3, 'Authentic flavors and friendly staff.', '2024-06-09', 'pending', 172);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (10, 87, 8.4, 'A bit overpriced for the portion size.', '2026-02-15', 'approved', 173);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (9, 87, 5.0, 'Solid choice for a casual dinner.', '2024-12-19', 'approved', 174);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (2, 88, 7.6, 'The dessert was the highlight of the meal.', '2025-12-04', 'pending', 175);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (27, 88, 9.9, 'Hard to find parking nearby.', '2025-11-13', 'approved', 176);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (27, 89, 9.1, 'Standard fare, nothing extraordinary.', '2024-10-11', 'approved', 177);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (7, 89, 9.7, 'The spice level was just right.', '2024-12-24', 'approved', 178);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (18, 90, 4.6, 'A hidden gem in the neighborhood.', '2024-02-28', 'approved', 179);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (40, 90, 6.2, 'Solid choice for a casual dinner.', '2024-10-30', 'removed', 180);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (37, 91, 6.7, 'Solid choice for a casual dinner.', '2025-03-02', 'approved', 181);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (27, 91, 9.7, 'The service was a bit slow, but the food made up for it.', '2024-08-25', 'removed', 182);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (35, 92, 9.4, 'Excellent value for money.', '2025-10-05', 'approved', 183);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (40, 92, 9.4, 'Best place near campus for a quick bite.', '2025-08-13', 'pending', 184);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (20, 93, 3.6, 'Authentic flavors and friendly staff.', '2024-04-04', 'pending', 185);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (7, 93, 1.0, 'Very clean and well-maintained.', '2024-12-21', 'approved', 186);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (1, 94, 7.6, 'Solid choice for a casual dinner.', '2025-08-08', 'approved', 187);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 94, 3.4, 'The spice level was just right.', '2024-05-13', 'approved', 188);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 95, 2.5, 'The seating area was quite cramped.', '2025-10-23', 'approved', 189);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 95, 9.5, 'The seating area was quite cramped.', '2025-07-15', 'approved', 190);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (19, 96, 9.9, 'Excellent value for money.', '2024-04-12', 'approved', 191);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (36, 96, 3.7, 'The ambiance is perfect for a date night.', '2025-09-06', 'approved', 192);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 97, 4.9, 'The dessert was the highlight of the meal.', '2025-12-13', 'removed', 193);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (29, 97, 4.2, 'Standard fare, nothing extraordinary.', '2025-12-26', 'approved', 194);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (7, 98, 2.6, 'Perfect for group hangouts.', '2024-01-31', 'removed', 195);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (39, 98, 4.5, 'A hidden gem in the neighborhood.', '2025-12-11', 'pending', 196);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (32, 99, 4.9, 'A bit overpriced for the portion size.', '2026-02-09', 'removed', 197);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (38, 99, 6.6, 'The seating area was quite cramped.', '2025-01-25', 'removed', 198);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (3, 100, 3.7, 'A hidden gem in the neighborhood.', '2025-07-24', 'removed', 199);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (16, 100, 9.8, 'Solid choice for a casual dinner.', '2025-01-12', 'removed', 200);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 101, 6.4, 'Hard to find parking nearby.', '2026-01-30', 'approved', 201);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (5, 101, 2.2, 'The dessert was the highlight of the meal.', '2024-09-04', 'pending', 202);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (7, 102, 1.6, 'The wait time was longer than estimated.', '2024-09-21', 'approved', 203);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (26, 102, 7.2, 'The wait time was longer than estimated.', '2025-10-08', 'pending', 204);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (22, 103, 9.2, 'The wait time was longer than estimated.', '2025-12-06', 'pending', 205);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (35, 103, 4.1, 'Excellent value for money.', '2025-04-01', 'approved', 206);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (4, 104, 2.3, 'The ambiance is perfect for a date night.', '2024-07-04', 'approved', 207);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (4, 104, 6.0, 'The spice level was just right.', '2024-07-15', 'approved', 208);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (6, 105, 6.4, 'The spice level was just right.', '2024-10-10', 'approved', 209);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (19, 105, 8.0, 'Hard to find parking nearby.', '2025-10-24', 'approved', 210);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (30, 106, 4.8, 'Best place near campus for a quick bite.', '2024-03-12', 'removed', 211);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (25, 106, 5.4, 'Not many vegetarian options available.', '2024-08-25', 'pending', 212);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (28, 107, 4.1, 'Will definitely be coming back again!', '2025-03-15', 'removed', 213);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (28, 107, 6.8, 'Authentic flavors and friendly staff.', '2025-07-11', 'pending', 214);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 108, 1.2, 'Very clean and well-maintained.', '2026-02-15', 'approved', 215);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (16, 108, 3.0, 'Perfect for group hangouts.', '2025-01-18', 'removed', 216);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (32, 109, 1.5, 'Best place near campus for a quick bite.', '2024-03-10', 'approved', 217);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (8, 109, 7.6, 'Perfect for group hangouts.', '2025-11-14', 'approved', 218);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 110, 4.7, 'The ambiance is perfect for a date night.', '2026-01-13', 'pending', 219);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (30, 110, 9.6, 'Great food and atmosphere!', '2024-08-03', 'removed', 220);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (25, 111, 10.0, 'A hidden gem in the neighborhood.', '2025-07-21', 'approved', 221);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (40, 111, 1.9, 'Highly recommend the signature dish.', '2025-01-01', 'pending', 222);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (31, 112, 1.9, 'Excellent value for money.', '2024-08-04', 'removed', 223);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (18, 112, 9.6, 'Great food and atmosphere!', '2025-04-08', 'removed', 224);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (35, 113, 6.2, 'The seating area was quite cramped.', '2025-03-22', 'approved', 225);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (14, 113, 8.6, 'Very clean and well-maintained.', '2024-01-20', 'pending', 226);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (39, 114, 1.0, 'Hard to find parking nearby.', '2024-11-07', 'pending', 227);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 114, 2.6, 'Authentic flavors and friendly staff.', '2025-01-25', 'approved', 228);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (25, 115, 9.5, 'A hidden gem in the neighborhood.', '2026-01-24', 'approved', 229);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (11, 115, 2.1, 'The service was a bit slow, but the food made up for it.', '2024-10-09', 'approved', 230);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (31, 116, 3.6, 'The ambiance is perfect for a date night.', '2024-11-30', 'removed', 231);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (7, 116, 5.7, 'Great food and atmosphere!', '2025-03-02', 'removed', 232);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (29, 117, 9.9, 'Not many vegetarian options available.', '2024-06-15', 'pending', 233);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (11, 117, 7.7, 'Highly recommend the signature dish.', '2025-08-31', 'approved', 234);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (31, 118, 1.1, 'The spice level was just right.', '2025-06-08', 'removed', 235);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (19, 118, 2.0, 'Solid choice for a casual dinner.', '2025-10-20', 'approved', 236);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (6, 119, 7.1, 'Best place near campus for a quick bite.', '2025-04-30', 'approved', 237);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (28, 119, 5.5, 'A bit overpriced for the portion size.', '2024-06-26', 'pending', 238);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (26, 120, 6.6, 'Hard to find parking nearby.', '2025-05-03', 'removed', 239);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (1, 120, 6.7, 'The seating area was quite cramped.', '2025-12-28', 'approved', 240);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (2, 121, 5.0, 'A bit overpriced for the portion size.', '2024-07-02', 'pending', 241);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (40, 121, 4.6, 'Solid choice for a casual dinner.', '2024-09-28', 'removed', 242);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (13, 122, 7.5, 'Hard to find parking nearby.', '2024-12-07', 'removed', 243);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (37, 122, 9.8, 'The wait time was longer than estimated.', '2024-04-27', 'removed', 244);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (7, 123, 3.8, 'The spice level was just right.', '2024-11-14', 'removed', 245);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (16, 123, 1.7, 'Not many vegetarian options available.', '2025-06-03', 'removed', 246);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (35, 124, 2.7, 'A bit overpriced for the portion size.', '2025-09-19', 'removed', 247);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (39, 124, 8.6, 'The ambiance is perfect for a date night.', '2025-05-13', 'removed', 248);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (38, 125, 8.2, 'Excellent value for money.', '2026-04-13', 'removed', 249);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (16, 125, 2.1, 'Not many vegetarian options available.', '2025-01-22', 'removed', 250);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (7, 126, 4.6, 'The service was a bit slow, but the food made up for it.', '2025-02-25', 'approved', 251);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 126, 5.0, 'Will definitely be coming back again!', '2024-03-05', 'removed', 252);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (5, 127, 1.9, 'The spice level was just right.', '2024-04-09', 'approved', 253);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (31, 127, 4.8, 'Very clean and well-maintained.', '2024-11-08', 'approved', 254);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (36, 128, 8.3, 'The spice level was just right.', '2024-08-18', 'approved', 255);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (35, 128, 9.5, 'A bit overpriced for the portion size.', '2025-05-20', 'removed', 256);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (10, 129, 4.5, 'A hidden gem in the neighborhood.', '2024-08-07', 'approved', 257);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (11, 129, 1.7, 'Authentic flavors and friendly staff.', '2026-04-10', 'approved', 258);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (13, 130, 2.2, 'The wait time was longer than estimated.', '2026-03-05', 'removed', 259);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (16, 130, 3.4, 'The seating area was quite cramped.', '2025-03-20', 'removed', 260);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (33, 76, 3.6, 'The dessert was the highlight of the meal.', '2026-03-02', 'pending', 261);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (32, 125, 9.4, 'The wait time was longer than estimated.', '2024-06-21', 'approved', 262);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (32, 35, 5.9, 'The seating area was quite cramped.', '2025-07-26', 'removed', 263);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (16, 20, 3.5, 'The wait time was longer than estimated.', '2025-11-27', 'approved', 264);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (26, 32, 4.6, 'The service was a bit slow, but the food made up for it.', '2025-04-14', 'removed', 265);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (15, 81, 3.2, 'The ambiance is perfect for a date night.', '2024-10-22', 'removed', 266);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (36, 125, 6.1, 'Hard to find parking nearby.', '2024-01-03', 'removed', 267);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (32, 100, 9.9, 'Standard fare, nothing extraordinary.', '2025-07-02', 'removed', 268);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (23, 14, 6.2, 'The ambiance is perfect for a date night.', '2025-03-29', 'removed', 269);
insert into Review (user_id, restaurant_id, rating, review_text, review_date, review_status, review_id) values (25, 75, 8.1, 'Will definitely be coming back again!', '2024-10-30', 'pending', 270);
